name: Accessibility Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Pa11y
        run: npm install -g pa11y

      - name: zola-build
        uses: knzai/zola-cli@build
        with:
          root: wittallen-com
          force: true # The anemone theme dumps stuff there by default

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: zola-serve
        run: |
          cd wittallen-com/
          zola serve

  accessibility:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run accessibility test
        run: pa11y https://127.0.0.1:1111 --timeout 60000 --wait 30000 #--reporter html > pa11y-report.html


      # - name: Upload report
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: pa11y-report
      #     path: pa11y-report.html

      # - uses: a11ywatch/github-action@v2.1.10
      #   with:
      #     WEBSITE_URL: https://wittallen.net
      #     # SITE_WIDE: true
      #     # SUBDOMAINS: true
      #     # TLD: false
      #     SITEMAP: true
      #     FAIL_ERRORS_COUNT: 15
      #     LIST: true
      #     FIX: false
      #     UPGRADE: false
      #     UPLOAD: true
      #     COMPUTER_VISION_SUBSCRIPTION_KEY: ${{ secrets.COMPUTER_VISION_SUBSCRIPTION_KEY }}
      #     COMPUTER_VISION_ENDPOINT: ${{ secrets.COMPUTER_VISION_ENDPOINT }}
      #   env:
      #     DEFAULT_RUNNERS: htmlcs,axe
      #     PAGEMIND_IGNORE_WARNINGS: true
      #     AI_DISABLED: false
